Add http examples for example DB endpoints
BigLNotation/parkinsons_pulse_service pull request #12
Opened 2024-08-24 03:32 UTC by LeavesOfFall

2024-08-26 07:24 UTC, andrewqqiu approved these changes
i see no issue with this LGTM

2024-08-26 21:49 UTC, Jack17432 requested changes
Just move them around

2024-08-26 21:49 UTC, Jack17432 commented on http/database_example.http
> +}
These do two different things so please put them in separate files

2024-08-26 21:49 UTC, Jack17432 commented on http/database_example.http
> +GET {{address}}/read/1
If that one is an ID please move it be a variable so that we know what is required and what is a variable

2024-08-26 21:49 UTC, Jack17432 commented on http/database_example.http
> +	"number": 399
Same for these, please move the values to veriables

2024-08-26 21:50 UTC, Jack17432 requested changes

2024-08-26 21:50 UTC, Jack17432 commented on http/database_example.http
> +GET {{address}}/read/1
What is the return structure?

2024-08-26 21:50 UTC, Jack17432 commented on http/database_example.http
> +PUT {{address}}/write
Does this return the created object or just a success or fail?

2024-09-11 05:22 UTC, Jack17432 approved these changes
lgtm!

2024-09-11 05:22 UTC, merged